---

# remove previously added entries for loopback line; all hostnames will be added via the local ip address
- name: ensure {{ansible_hostname}} is in the /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 {{ansible_hostname}} localhost'
    line: "127.0.0.1 localhost localhost.localdomain"
    owner: root
    group: root
    mode: 0644