---

- hosts: api
  vars_files: 
    - "vars/{{ env }}.yml"
  tasks: 
    - name: install tomcat
      apt: 
        name: tomcat8
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - set_fact:
        temp_java_opts: "{{ tomcat.JAVA_OPTS }}"

    - name: set final JAVA_OPTS
      set_fact:
        temp_java_opts: "{{ temp_java_opts }} -D{{ item.key}}='{{ item.value }}'"
      with_dict: "{{application.env}}"

    - name: change java opts for variables
      lineinfile: 
        path: /etc/default/tomcat8
        regexp: '^JAVA_OPTS='
        line: "JAVA_OPTS=\"{{ temp_java_opts }}\""
        backrefs: yes
      notify: restart tomcat8
      become: true

    - name: deploy tomcat application
      copy:
        src: "{{ artifact_path }}"
        dest: "{{ tomcat.deploy_folder }}/{{ artifact_path | basename }}"
        owner: tomcat8
        group: tomcat8
        mode: 0644
      notify: restart tomcat8
      become: true

    - name: tomcat8 service is enable and running
      service:
        name: tomcat8
        state: started
      become: true
      
  handlers:
    - name: restart tomcat8
      service:
        name: tomcat8
        state: restarted
      become: true